DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS rainfall;

CREATE TABLE locations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    placename TEXT NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL
);

CREATE TABLE rainfall (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rainfalldate DATE NOT NULL,
    rainfall FLOAT NOT NULL
);